permalink: /:year:month:day/:title
url: #Your url here
baseurl:

# variables
name: mikaji
description: Software Engineer. Living in Tokyo.
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE", ".sass-cashe"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
